# Generated by Django 5.2.5 on 2025-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
