# Generated by Django 5.2.5 on 2025-09-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
