# Generated by Django 5.2.5 on 2025-09-08 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_restaurant_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='organization',
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
