# Generated by Django 5.2.5 on 2025-09-08 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_branch_organization_branch_restaurant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
