# Generated by Django 5.2.5 on 2025-09-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_restaurant_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='users',
        ),
    ]
