# Generated by Django 5.2.5 on 2025-09-10 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='organizations_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
