# Generated by Django 5.2.5 on 2025-09-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_guest_name_reservation_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customerr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.customer'),
        ),
    ]
