# Generated by Django 5.2.5 on 2025-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('CUSTOMER', 'Customer')], default='WAITER', max_length=10),
        ),
    ]
