# Generated by Django 5.2.5 on 2025-10-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sale_saleitem'),
        ('organizations', '0012_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.restaurant'),
        ),
    ]
