# Generated by Django 5.2.5 on 2025-09-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0003_alter_item_restaurant'),
        ('organizations', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.restaurant'),
        ),
    ]
