# Generated by Django 5.2.5 on 2025-09-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
    ]
