# Generated by Django 5.2.5 on 2025-10-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
